
// This file has been generated by the GUI designer. Do not modify.
namespace MPANAGTK.Frontend.FoodChemistry
{
	public partial class FoodChemistry
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MPANAGTK.Frontend.FoodChemistry.FoodChemistry
			this.Name = "MPANAGTK.Frontend.FoodChemistry.FoodChemistry";
			this.Title = global::Mono.Unix.Catalog.GetString("FoodChemistry");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
